CREATE TABLE AUTHORS (
authors_ID INT,
authors_FIRSTNAME VARCHAR (100),
authors_LASTNAME VARCHAR (100)
);

CREATE TABLE PUBLISHERS (
PUBLISHERS_ID INT,
PUBLISHERS_NAME VARCHAR (100),
PUBLISHERS_COUNTRYOFORIGIN VARCHAR (100)
);

CREATE TABLE BOOKS (
BOOKS_ID INT,
BOOKS_TITLE VARCHAR (150),
BOOKS_ISBN INT,
BOOKS_PRICE DECIMAL (10,2)
);


--PROBLEM 2

CREATE TABLE PATIENTS (
PATIENTS_ID INT,
PATIENTS_FIRSTNAME VARCHAR (100),
PATIENTS_LASTNAME VARCHAR (100),
PATIENTS_DATE_OF_BIRTH DATE,
PATIENTS_PHONE_NUMBER INT (15),
PATIENTS_DATE DATE 
);

CREATE TABLE DOCTORS (
DOCTORS_ID INT,
DOCTORS_FIRSTNAME VARCHAR (100),
DOCTORS_LASTNAME VARCHAR (100),
DOCTORS_MEDICAL_SPECIALTY VARCHAR (100),
DOCTORS_LICENSED_DATE DATE
);

CREATE TABLE APPOINTMENTS (
APPOINTMENTS_ID INT,
APPOINTMENTS_FOREIGN_KEYS VARCHAR (100),
APPOINTMENTS_DATE DATE,
APPOINTMENTS_TIME TIME,

);

