CREATE TABLE AUTHORS (
AUTHORS_ID INT,
FIRST_NAME VARCHAR (100),
LAST_NAME VARCHAR (100)
);

CREATE TABLE PUBLISHERS (
PUBLISHERS_ID INT,
FIRST_NAME VARCHAR (100),
COUNTRY_OF_ORIGIN VARCHAR (100)
);

CREATE TABLE BOOKS (
BOOKS_ID INT,
TITLE VARCHAR (150),
ISBN INT,
PRICE DECIMAL (10,2)
);


--PROBLEM 2

CREATE TABLE PATIENTS (
PATIENTS_ID INT,
FIRST_NAME VARCHAR (100),
LAST_NAME VARCHAR (100),
DATE_OF_BIRTH DATE,
PHONE_NUMBER INT (15),
DATE_CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP

CREATE TABLE DOCTORS (
DOCTORS_ID INT,
FIRST_NAME VARCHAR (100),
LAST_NAME VARCHAR (100),
MEDICAL_SPECIALTY VARCHAR (100),
LICENSED_DATE DATE
);

CREATE TABLE APPOINTMENTS (
APPOINTMENTS_ID INT,
PATIENTS_ID INT,
DOCTORS_ID INT,
DATE_TIME TIMESTAMP,
REASON VARCHAR (200),
APPOINTMENTS_STATUS ENUM('Scheduled', 'Completed', 'Cancelled', 'No-Show') DEFAULT 'Scheduled'
);

--problem 3
CREATE TABLE DEPARTMENTS (
DEPARTMENTS_ID SERIAL PRIMARY KEY, 
DEPARTMENTS_NAME VARCHAR (100) UNIQUE,
OFFICE_LOCATION VARCHAR (100)
);

CREATE TABLE COURSES (
COURSE_ID SERIAL PRIMARY KEY,
COURSE_CODE VARCHAR (20) UNIQUE,
TITLE VARCHAR (255),
CREDITS TINYINT UNSIGNED NOT NULL CHECK (credits > 0),
credits SMALLINT CHECK (credits > 0),
DEPARTMENTS_ID INTEGER NOT NULL,
PREREQUISITE_COURSE_ID INTEGER,
CONSTRAINT FK_DEPARTMENTS
FOREIGN KEY (DEPARTMENTS_ID)
REFERENCES DEPARTMENTS(DEPARTMENTS_ID)
ON DELETE CASCADE,
CONSTRAINT FK_PREREQUISITE
FOREIGN KEY (PREREQUISITE_COURSE_ID)
REFERENCES COURSES (COURSES_ID )
ON DELETE SET NULL
);
